[package]
name = "rust-script"
version = "0.22.0"
edition = "2018"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
description = "Command-line tool to run Rust \"scripts\" which can make use of crates."
homepage = "https://rust-script.org"
documentation = "https://rust-script.org"
repository = "https://github.com/fornwall/rust-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]
categories = ["command-line-utilities", "development-tools"]

exclude = [
    "_config.yml",
    "CNAME",
    ".github",
    "target"
]

[dependencies]
clap = "3.1.2"
dirs-next = "2"
env_logger = "0.9"
lazy_static = "1"
log = "0.4"
proc-macro2 = { version = "1.0.39", features = ["span-locations"] }
pulldown-cmark = "0.9"
regex = "1"
rustversion = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha-1 = "0.10"
syn = { version = "1.0.96", features = ["full", "extra-traits", "visit"] }
tempfile = "3"
toml = "0.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.10"

[target.'cfg(unix)'.dependencies]
atty = "0.2"

[dev-dependencies]
scan-rules = "0.2"

[profile.release]
lto = true
